### ISSUE TITLE
launch.py: error: no such option: --desired_truncation_level

### ISSUE THREAD

**Issue by andyyuan78** [kzhai/InfVocLDA#2]
ubgpu@ubgpu:~/github/InfVocLDA/src$ python -m infvoc.launch --input_directory=../input/ --output_directory=../output/ --corpus_name=de-news --desired_truncation_level=4000 --number_of_topics=10 --number_of_documents=9800 --vocab_prune_interval=10 --batch_size=100 --alpha_beta=1000
Usage: launch.py [options]

launch.py: error: no such option: --desired_truncation_level
ubgpu@ubgpu:~/github/InfVocLDA/src$

**Comment by kzhai** [comment]
Hi, Andy,

The command is "truncation_level" instead of "desired_truncation_level".
Please refer to "--help" command for more information.

Best,
Ke

**Comment by andyyuan78** [comment]
ok,  i just copy it from readme

**Comment by kzhai** [comment]
Hi, Andy,

Sorry, I will update that in readme. Thanks for reporting the bug.

Best,
Ke
