### ISSUE TITLE
batch_size, e_step function

### ISSUE THREAD

**Issue by raphaelsty** [kzhai/InfVocLDA#5]
Hello, I would really like to add your lda with an infinite vocabulary feature to the Creme library (online machine learning library) https://github.com/creme-ml/creme

I have a doubt about the e_step function, you initiate the batch_size variable from the length of the wordids variable however a few lines later, your comment suggests that batch_size is an integer that refers to the number of documents.

Here len(wordids) = number of words in the document if you set batch_size to 1.

Did you voluntarily initialize the batch_size variable from len(wordids)? Should
```batch_size = self._batch_size```?

https://github.com/kzhai/InfVocLDA/blob/05a87890d613b07f7b0c2d2bb6c79aad39e2f75d/src/infvoc/hybrid.py#L279-L280

Your comment:

https://github.com/kzhai/InfVocLDA/blob/05a87890d613b07f7b0c2d2bb6c79aad39e2f75d/src/infvoc/hybrid.py#L292-L293

Thank you in advance for your feedback to confirm that ```batch_size = len(wordids)```

Raphaël

**Comment by kzhai** [comment]
Hi, Raphael,

Thanks for your interest.
As I recall, you can set the batch size to any arbitrary number. Usually,
default it to a small value, e.g., 1 or 10, would work just fine. Also,
setting it to 1 also simulates the *real* online case. Feel free to set it
to any number.

Best,
Ke

**Comment by raphaelsty** [comment]
Thank you :-)
